"use client";

import { useState } from 'react';
import { PDFDocument, rgb } from 'pdf-lib';

export default function PDFOverlay() {
  const [isProcessing, setIsProcessing] = useState(false);
  const [message, setMessage] = useState('');

  // Sample form schema for testing
  const sampleSchema = {
    formType: "GSA_TEST",
    fields: [
      { name: "firstName", x: 100, y: 700, fontSize: 12 },
      { name: "lastName", x: 250, y: 700, fontSize: 12 },
      { name: "address", x: 100, y: 650, fontSize: 10 },
      { name: "city", x: 100, y: 620, fontSize: 10 },
      { name: "state", x: 250, y: 620, fontSize: 10 },
      { name: "zip", x: 300, y: 620, fontSize: 10 },
    ]
  };

  // Sample form data (from Hawaii form)
  const sampleData = {
    firstName: "John",
    lastName: "Doe", 
    address: "123 Main Street",
    city: "Honolulu",
    state: "HI",
    zip: "96813"
  };

  const createBlankPDF = async () => {
    try {
      setIsProcessing(true);
      setMessage('Creating PDF...');

      // Create a blank PDF document
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([612, 792]); // Standard letter size

      // Add title
      page.drawText('GSA FORM TEST - PDF OVERLAY PROOF OF CONCEPT', {
        x: 50,
        y: 750,
        size: 14,
        color: rgb(0, 0, 0),
      });

      // Add form fields based on schema
      sampleSchema.fields.forEach(field => {
        const value = sampleData[field.name] || '';
        
        // Draw field label
        page.drawText(`${field.name.toUpperCase()}:`, {
          x: field.x - 80,
          y: field.y,
          size: 10,
          color: rgb(0.5, 0.5, 0.5),
        });

        // Draw field value
        page.drawText(value, {
          x: field.x,
          y: field.y,
          size: field.fontSize,
          color: rgb(0, 0, 0),
        });

        // Draw field box outline
        page.drawRectangle({
          x: field.x - 5,
          y: field.y - 5,
          width: 150,
          height: 20,
          borderColor: rgb(0.8, 0.8, 0.8),
          borderWidth: 1,
        });
      });

      // Add footer
      page.drawText('Generated by Bermuda App - PDF Overlay System', {
        x: 50,
        y: 50,
        size: 8,
        color: rgb(0.6, 0.6, 0.6),
      });

      // Save the PDF
      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      
      // Download the PDF
      const link = document.createElement('a');
      link.href = url;
      link.download = 'gsa-form-overlay-test.pdf';
      link.click();

      setMessage('PDF created successfully! Check your downloads.');
      
    } catch (error) {
      console.error('PDF creation error:', error);
      setMessage('Error creating PDF: ' + error.message);
    } finally {
      setIsProcessing(false);
    }
  };

  const overlayOnExistingPDF = async (file) => {
    try {
      setIsProcessing(true);
      setMessage('Processing existing PDF...');

      const arrayBuffer = await file.arrayBuffer();
      const pdfDoc = await PDFDocument.load(arrayBuffer);
      
      // Get the first page
      const pages = pdfDoc.getPages();
      const firstPage = pages[0];

      // Overlay our data
      sampleSchema.fields.forEach(field => {
        const value = sampleData[field.name] || '';
        
        firstPage.drawText(value, {
          x: field.x,
          y: field.y,
          size: field.fontSize,
          color: rgb(0, 0, 1), // Blue text to show overlay
        });
      });

      // Save the modified PDF
      const pdfBytes = await pdfDoc.save();
      const blob = new Blob([pdfBytes], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = 'overlayed-' + file.name;
      link.click();

      setMessage('PDF overlay completed! Check your downloads.');
      
    } catch (error) {
      console.error('PDF overlay error:', error);
      setMessage('Error overlaying PDF: ' + error.message);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    if (file && file.type === 'application/pdf') {
      overlayOnExistingPDF(file);
    } else {
      setMessage('Please select a valid PDF file.');
    }
  };

  return (
    <div className="max-w-2xl mx-auto p-6 bg-gray-800 rounded-lg">
      <h2 className="text-2xl font-bold text-white mb-6 text-center">
        PDF OVERLAY PROOF OF CONCEPT 🔥
      </h2>

      <div className="space-y-6">
        {/* Sample Data Display */}
        <div className="bg-gray-700 p-4 rounded">
          <h3 className="text-lg font-bold text-white mb-2">Sample Data:</h3>
          <pre className="text-green-400 text-sm">
            {JSON.stringify(sampleData, null, 2)}
          </pre>
        </div>

        {/* Sample Schema Display */}
        <div className="bg-gray-700 p-4 rounded">
          <h3 className="text-lg font-bold text-white mb-2">Sample Schema:</h3>
          <pre className="text-blue-400 text-sm">
            {JSON.stringify(sampleSchema, null, 2)}
          </pre>
        </div>

        {/* Actions */}
        <div className="space-y-4">
          <button
            onClick={createBlankPDF}
            disabled={isProcessing}
            className="w-full px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-600"
          >
            {isProcessing ? 'Processing...' : 'Create Test PDF (Blank + Overlay)'}
          </button>

          <div className="border-t border-gray-600 pt-4">
            <label className="block text-white mb-2">
              Upload existing PDF to overlay data:
            </label>
            <input
              type="file"
              accept=".pdf"
              onChange={handleFileUpload}
              disabled={isProcessing}
              className="w-full px-3 py-2 bg-gray-700 text-white rounded border border-gray-600"
            />
          </div>
        </div>

        {/* Status Message */}
        {message && (
          <div className="p-3 bg-gray-700 text-white rounded text-center">
            {message}
          </div>
        )}
      </div>
    </div>
  );
}
